### ISSUE TITLE
Fix flaky TestConfigureNetworkCreatesNewNetworkWhenNoNetworkExists

### ISSUE THREAD

**Issue by MrSerth** [openHPI/poseidon#532] opened 2024-01-02 11:58 UTC
I just experienced a new flaky test in [this run](https://github.com/openHPI/poseidon/actions/runs/7385435845/job/20090207686): `TestMainTestSuite/TestConfigureNetworkCreatesNewNetworkWhenNoNetworkExists`. The failing test should be verified and the underlying bug should be fixed.

**Comment by mpass99** [comment] 2024-02-27 21:43
The cause is one Goroutine that exists when the test starts but not after the test ends. The Goroutine is:
```
1 @ 0x447c27 0x474266
#	0x447c26	runtime.goexit1+0x46	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/proc.go:3850
```
Checking the [source](https://github.com/golang/go/blob/2c1e5b05fe39fc5e6c730dd60e82946b8e67c6ba/src/runtime/proc.go#L3850), we see that this is the line just before a Goroutine stops.

Therefore, we might assume that we are dealing with a race condition between closing all Goroutines of previous tests and starting a new test.
It might be enough to introduce a short timeout before starting another test, but as this is just about tests I would not introduce complicated production code to verify/wait for goroutines being closed..

**Closed** 2024-02-28 10:52 UTC
Labels: bug
