### ISSUE TITLE
Unreliable prewarming pool size

### ISSUE THREAD

**Issue by mpass99** [openHPI/poseidon#358] opened 2023-04-23 10:42 UTC
The number of idle runner is varying strongly out of unknown reasons.

<details>
  <summary>The number of runner decreases.</summary>
  <p>

- On the 18th from 7am till 1pm decreases from 5 to 2 for environment 29 and from 5 to 4 for environment 10.
- On the 20th from 6:27 am to 4 pm environment 29 decreases from 11 to 3 runners
  - Sentry `Stderr task finished with error`
    - `error executing command in allocation: task "default-task" is not running.`
- On the 21st from 5am to 11am from 6 to 4
- On the 22nd from 3am to 9pm from 5 to 2
- On the 23rd environment 10 from 6am to 9 pm from 5 to 4

  </p>
</details>

<details>
  <summary>The number of runner increases.</summary>
  <p>

- On the 18th at 8pm environment 10 has one additional runner.
  - `Apr 18 19:55:18 Main process exited, code=exited, status=2/INVALIDARGUMENT`
  - `Apr 18 19:55:20 Started Poseidon`
  - Sentry `Couldn't scale environment`
- On the 19th at 6:30am an rapid increase to 8 idle runner (both environments).
- At 6:42am environment 29 goes to 12 runner
- At 6:46am environment 29 goes to 15 runner
- At 8:28am environment 29 increased by 1
  - `Apr 19 08:28:00 Main process exited, code=exited, status=2/INVALIDARGUMENT`
  - `Apr 19 08:28:02 Started Poseidon`
  - Sentry `Couldn't scale environment`
- On the 20th at 3am environment 10 from 4 to 7
  - `Apr 20 03:00:00 Stopping Poseidon`
  - `Apr 20 03:00:47 Started Poseidon`
  - Sentry `Couldn't scale environment`
  - 6x Sentry `Other Desired Status`
    - This warning is assumed to be related to a decreased runner count
    - Only template jobs and runner of environment 11 affected
    - Not related to this issue. See #357 instead
  - InfluxDB: Many allocations are added 7 or 8 times in the same second `03:01:50`
  - Nomad Server upgrade
- On the 21st at 3am environment 29 increased to 6
  - Sentry `Stderr task finished with error`
    - Nomad error `Unexpected response code: 500 (rpc error: failed to get conn: rpc error: lead thread didn't get connection)`
  - Sentry `Error executing the request`
    - Nomad error `Unexpected response code: 500 (rpc error: failed to get conn: dial tcp [ip]:4647: connect: connection refused)`

  </p>
</details>

Assumptions:
- Two different causes
- [x] The number of runner decreases
  - Some requested runner do not result in a started runner
  - ~~ToDo: inspect Influx data, if there are pending runner logged without being started afterward~~ Updates are not logged
  - ~~ToDo: Inspect the Nomad Logs if the missing runner was requested~~ Done
  - ~~ToDo: Evaluate Debug Logs~~
  - The environment is lost after unattended-upgrades and thus the pre-warming pool size reported drops to 0 (see #408). 
- [ ] The number of runner increases.
  - ToDo: Evaluate the correlation with the unattended upgrades
  - When an allocation gets restarted or rescheduled, the number increases temporarily (see #405).

**Comment by mpass99** [comment] 2023-04-23 13:05
> * On the 18th from 7am till 1pm decreases from 5 to 2 for environment 29 and from 5 to 4 for environment 10.

We have two requested runner but only one started runner. No errors
``` log
time="2023-04-20T06:27:32.695214Z" level=debug code=200 duration="476.766µs" method=POST path=/api/v1/runners user_agent="Faraday v2.7.4"
time="2023-04-20T06:27:33.224575Z" level=debug code=200 duration=2.906583ms method=POST path=/api/v1/runners user_agent="Faraday v2.7.4"
time="2023-04-20T06:27:33.891399Z" level=debug msg="Runner started" id=29-6f0c933a-df44-11ed-8076-fa163e079f19 package=runner startupDuration=269.144776ms
```

**Comment by MrSerth** [comment] 2023-04-24 06:52
Starting from yesterday afternoon (April 23rd, at around 3:41pm according to Sentry), we had major issues again. For environment ID 29 no runner was available and I had to sync the environment manually this morning. See [POSEIDON-J](https://codeocean.sentry.io/issues/2817573153/)

**Comment by MrSerth** [comment] 2023-04-25 18:28
We just had these issues once again. I've increased the pool to 15 (so that it's less stressful for me to check), but we should continue investigating here.

**Comment by mpass99** [comment] 2023-05-06 20:30
> - The number of runner decreases 
>   - Inspect the Nomad Logs if the missing runner was requested

I inspected the Nomad logs for the case `On the 20th from 6:27 am to 4 pm environment 29 decreases from 11 to 3 runners`.

In the Poseidon log you see that in that minute 11 runners were requested. In the Nomad log you see that those 11 runner have been started. But, in the Poseidon log you see that Poseidon recognises only 10 started runner. [See](https://github.com/openHPI/poseidon/files/11413340/missed-runner-062733.log)

Therefore, the issue must be in the handling of the Nomad events (like for other recent PRs i.e. #343).

**Comment by mpass99** [comment] 2023-05-10 11:22
Monitoring the Nomad events (introduced with #356) has shown that all expected events are received.

We have evaluated the occurences of one lost runner at [`May  9 09:44:39`](https://github.com/openHPI/poseidon/files/11441174/nomad_events_23-05-09_09-44.log) and [`May  9 12:07:55`](https://github.com/openHPI/poseidon/files/11441171/nomad_events_23-05-09_12-37.log).

In both cases Poseidon receives Nomad Events with the right topic `Allocation`, the right Client status `pending`, and the right desired status `run` (also the running event afterwards). Still, the runner is not added to the idle runner. Furthermore, not even the pending event is recognized as the measurement `poseidon_nomad_allocations` does not contain the allocation or job id (until the next Poseidon restart).

Even after having a 101st look, I could not identify a condition leading to ignoring this event. Therefore, we want to add further debug statements with #371 reducing the bug vector.

**Comment by mpass99** [comment] 2023-05-11 12:37
The 102nd look (and the additional debug statements) helped.

We see in the [Poseidon logs](https://github.com/openHPI/poseidon/files/11452089/poseidon_may_11.log) the difference between a successful and an unsuccessful Nomad event handling.
When we compare the [Nomad events](https://github.com/openHPI/poseidon/files/11452097/Nomad_events_may_11.log) for those two cases, we see that in the unsuccessful case the event `Allocation` (topic), `AllocationUpdated` (type), `pending` (ClientStatus) is missing. It seems that this event is common but optional.

Still, both cases contain the event `Allocation`, `PlanResult`, `pending`. By not ignoring `PlanResult` event as we did, the problem of decreasing runners should be solved. #372 implements this fix.

An alternative solution might be to listen to the `Job` (topic) events as they are also `pending` and `running` and have the advantage of dealing just with the Job ID (runner id) as we do in all the rest of Poseidon.

**Comment by MrSerth** [comment] 2023-05-11 21:42
Thanks for continuously checking the event stream; your log and event snippets made it really easy to get the difference for me! I am glad you started working on a first fix with #372, and I am eager to see whether this improves (and hopefully resolves) our situation.

For the long term, changing the code to listen to the `Job` (rather than `Allocation`) also sounds good, especially when this is what we usually do in the code. My only concern would be that this refactoring might also introduce some errors, whereas we hopefully have a suitable solution with `Allocation`. Do you remember why `Allocation` was chosen in the first place?

**Comment by mpass99** [comment] 2023-05-12 16:09
Regarding the increased amount of idle runners my new working theory is that this issue is connected with the decreased runners.

The idle runner decrease because Poseidon does not handle the Nomad events correctly, but the runner / allocation / Docker container is started anyway.
On a Poseidon restart all runners are loaded from Nomad including those that led to the decreased amount (compare `29-1d5617f6-eefd-11ed-84c6-fa163e079f19`). Therefore, we have as many runner to much as we lost before over time.
With the unattended upgrades it is similar, as Docker gets restarted and therefore all allocations are reported again to Poseidon (including those that led to the decreased idle runner amount).

Let's observe this based on our new deployment including #372.

**Comment by mpass99** [comment] 2023-05-21 18:30
The number of runners was further increasing. In the last 5 days, it was increasing 4 times. Each increased the prewarming pool size by about 25%. Each occurrence was between 6 and 7am and is correlating with the unattended upgrade (aka `apt-daily-upgrade.service`).

With #381, we solve the bug of these specific cases: The unattended upgrade was restarting Docker. This led to all container being restarted. This case is handled by Poseidon by re-adding the runner to the idle runners. By doing so, we also added the restarted used runners to the idle runner. From an isolation point-of-view this is okay, but it results in too many runners. We solve this issue by deleting the restarted used runners after they restarted. This may not be very efficient resource-wise as we are deleting a clean runner.

With #380, we introduce a Sentry notification for the case of too many runners. Also, we are no longer creating more runners if we already have more than required.

**Comment by MrSerth** [comment] 2023-05-26 20:04
Thanks, sounds good. I like the two fixes so far. For the first one referring to #381: Since you mentioned that the issue is caused by Docker restarting, is the increased number of runners caused by Poseidon or Nomad "doubling" the temporary lost allocations? And is there a Docker / Nomad option to prevent those containers from being restarted?

**Comment by mpass99** [comment] 2023-05-28 22:19
> is the increased number of runners caused by Poseidon or Nomad "doubling" the temporary lost allocations?

The term `lost allocation` is misleading in this context as in this case in Nomad's understanding the allocation is not `lost` but `failed`.
It is Poseidon's fault that it moves/adds the restarted before-used runners to the idle runners.

> And is there a Docker / Nomad option to prevent those containers from being restarted?

Clever approach! In our environment, Docker stops and deletes all container when the Docker daemon restarts. (This behaviour could be adjusted[[1]](https://docs.docker.com/config/containers/start-containers-automatically/)). Instead, Nomad restarts the Allocation when it fails (i.e. due to a Docker restart). This behaviour is controlled by the Job Specification[[2]](https://developer.hashicorp.com/nomad/docs/job-specification/restart). In our case,

https://github.com/openHPI/poseidon/blob/26ca7e459755a8500000daa9f2d934db5d17031e/internal/environment/template-environment-job.hcl#L48-L50

the default of 3 restart attempts is being used. With #383 we shift the control over the restarts to Poseidon. With these changes we might increase the number of [POSEIDON-13](https://codeocean.sentry.io/issues/2889730393/) `Allocation failure`.

**Comment by MrSerth** [comment] 2023-05-29 16:35
Thanks for the explanation and alternative! Regarding the latter, I am still not sure whether I got the difference between a restart and a reschedule in Nomad: How do they differ, and when is which part of the job definition used? Can we make use of this differentiation?

Besides that, I am still not sure what exactly happens when Nomad decides to restart an allocation. Let's image, a Docker Daemon restart occurs. In this case, the allocations are (correctly) marked as failed by Nomad, since they are no longer available. I assume, Poseidon gets a corresponding event. Now, Nomad tries to restart / reschedule the allocations, which (in turn) would all of them reset to a clean state, does it? And simultaneously, for each failed allocation, Poseidon asks for another one, thus causing an increase in the runners?

Since these cases are, currently, mostly caused by the unattended upgrades, can we further control this process? For example, by configuring #369, disallowing the Docker Daemon to be restarted as long as Nomad is running (modifying the systemd config) or by installing updates only on a node shutdown `unattended_install_on_shutdown`(see [here](https://github.com/hifis-net/ansible-role-unattended-upgrades))?

Otherwise, I also like the various ideas you mentioned (temporary increase, #381, extend `MarkRunnerAsUsed`, #383). While I think it is best to shortly discuss the advantages and limitations, my general statement would be: Having a lack of idle runners is worse in comparison to too many idle runners (both in comparison to the requested pool size), and a lack should be prevented. During a short period of time, having more idle runners than requested is fine, we should just ensure that the numbers don't sum up over time.

**Comment by MrSerth** [comment] 2023-05-30 17:43
During our discussion today, we decided the following:
- [ ] First, deploy the latest changes and observe how they behave. We are especially interested to see how fast an increase in pool size is reduced (and whether it stabilizes again) after the recent changes in #380 
- [ ] Second, if the changes are not sufficient, proceed with one of the solutions discussed above (https://github.com/openHPI/poseidon/pull/381, extend `MarkRunnerAsUsed`, https://github.com/openHPI/poseidon/pull/383)
- [ ] Unrelated to our observation, we decided to configure `unattended_install_on_shutdown` and tackle https://github.com/openHPI/poseidon/issues/369. For the first part, I already created a corresponding pull request.

**Comment by MrSerth** [comment] 2023-05-31 22:46
I deployed the latest changes of our current `main` branch to production & staging. This deployment also included the change for `unattended_install_on_shutdown`.

**Comment by mpass99** [comment] 2023-06-03 16:45
> We are especially interested to see how fast an increase in pool size is reduced (and whether it stabilizes again) after the recent changes in #380

Since the deployment of #380, the pool size has been reduced and stabilized fast to the defined sized - it depends on the usage but is usually below 30 seconds. But, now that we monitor increased prewarming pool sizes more precisely, we noticed that it happens frequent - about 20 times per day ([POSEIDON-2N](https://codeocean.sentry.io/issues/4220082532)).

As the Sentry event is coupled with one less runner being requested and we do not have too few runners over time, the warning seems to be legitimate. Also, this means that the restart of the Docker service (as targeted with #381 and #383) is not the (only) reason behind the increased prewarming poolsize. But, based on this we would also expect about 20 additional runner per day before the deployment of #380 which was not the case.

The reason behind the additional runners could not be identified on the first look.

**Comment by MrSerth** [comment] 2023-07-06 18:23
The situation stabilized recently. Still, we sometimes observe a reduced pre-warming pool size, such as these days for environment 29 on production (desired 15, reported 13). Is the cause for this reduction related to one of the ones listed in this issue?

**Comment by mpass99** [comment] 2023-07-07 17:39
Thank you for noticing it. The missing runners are gone since `2023-07-02 15:02:38`.
It was probably a user OOM killing the allocations `29-aef4cc88-18e1-11ee-bcae-fa163e079f19`, `29-57cb53b6-18e7-11ee-bcae-fa163e079f19`, and `29-8171bd8c-18e4-11ee-bcae-fa163e079f19`. They got restarted and later the removed by its inactivity timer. These are examples for #396. This behavior was still possible because we have not performed an production deployment since this PR was merged.

**Comment by MrSerth** [comment] 2023-07-14 17:46
Sounds good, thanks for deploying and checking the logs again. I would just observe this issue a little longer, before we finally decide what to do with the new issue #405 and the two open PRs. Currently, there are some environments with a few more runners, but no environment has less runners than expected.

**Comment by MrSerth** [comment] 2023-07-17 17:41
We're finally closing this issue. The most important issues with the pre-warming pool size have been resolved, and two minor issues have been extracted (#405, #408). The other two PRs mentioned above (#381, #383) have been closed without merging, since their changes would only marginally improve the situation at very high (maintenance) costs.

**Closed by MrSerth** 2023-07-17 17:41 UTC
Labels: bug
